name: CymasphereApp
options:
  bundleIdPrefix: com.cymasphere
  deploymentTarget:
    iOS: 14.0
targets:
  CymasphereApp:
    type: application
    platform: iOS
    sources:
      - path: CymasphereApp
    settings:
      base:
        INFOPLIST_FILE: CymasphereApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.cymasphere.app
    info:
      path: CymasphereApp/Info.plist
      properties:
        CFBundleDisplayName: Cyma Site
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
