name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
      
      - name: List directory structure (for debugging)
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "App directory contents:"
          ls -la app || echo "App directory not found"
      
      - name: Make build script executable
        run: chmod +x ./build-local.sh
        
      - name: Run enhanced build script
        run: ./build-local.sh
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
      
      - name: Final Build Check
        run: |
          if [ -f ".next/server/pages/500.html" ]; then
            echo "✅ Build artifacts look good."
          else
            echo "❌ Build artifacts are missing."
            exit 1
          fi 