name: Build and Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Create Static Site
        run: |
          # Create a completely static site
          mkdir -p out/cymasphere-website/styles
          
          # Create CSS file
          cat > out/cymasphere-website/styles/main.css << 'EOL'
          :root {
            --font-sans: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            --color-primary: #4f46e5;
            --color-primary-light: #6366f1;
            --color-primary-dark: #4338ca;
            --color-secondary: #06b6d4;
            --color-secondary-light: #22d3ee;
            --color-secondary-dark: #0891b2;
            --color-background: #0f172a;
            --color-foreground: #f8fafc;
            --color-card: #1e293b;
            --color-card-foreground: #f8fafc;
            --color-border: #334155;
          }
          
          html, body {
            font-family: var(--font-sans);
            background-color: var(--color-background);
            color: var(--color-foreground);
            margin: 0;
            padding: 0;
            line-height: 1.5;
          }
          
          .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 1rem;
          }
          
          .card {
            background-color: var(--color-card);
            color: var(--color-card-foreground);
            border-radius: 0.5rem;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
          }
          
          .text-2xl {
            font-size: 1.5rem;
            line-height: 2rem;
          }
          
          .font-bold {
            font-weight: 700;
          }
          
          .mb-2 {
            margin-bottom: 0.5rem;
          }
          
          .mb-4 {
            margin-bottom: 1rem;
          }
          
          .mb-6 {
            margin-bottom: 1.5rem;
          }
          
          .p-4 {
            padding: 1rem;
          }
          
          .mx-auto {
            margin-left: auto;
            margin-right: auto;
          }
          
          .mt-8 {
            margin-top: 2rem;
          }
          
          .grid {
            display: grid;
          }
          
          .grid-cols-2 {
            grid-template-columns: repeat(2, minmax(0, 1fr));
          }
          
          .gap-4 {
            gap: 1rem;
          }
          
          .list-disc {
            list-style-type: disc;
          }
          
          .pl-5 {
            padding-left: 1.25rem;
          }
          
          .flex {
            display: flex;
          }
          
          .items-center {
            align-items: center;
          }
          
          .justify-between {
            justify-content: space-between;
          }
          EOL
          
          # Create index.html
          cat > out/cymasphere-website/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="utf-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <meta name="description" content="CymaSphere - Music Analysis Platform" />
              <title>CymaSphere</title>
              <link rel="stylesheet" href="styles/main.css" />
            </head>
            <body>
              <main class="container mx-auto p-4">
                <h1 class="text-2xl font-bold mb-4">CymaSphere</h1>
                <p class="mb-4">
                  A cutting-edge platform for music analysis and visualization.
                </p>
                <div class="card p-4 mb-6">
                  <h2 class="text-2xl font-bold mb-2">Static Site Demo</h2>
                  <p>
                    Welcome to the CymaSphere static site. This is a simplified version.
                  </p>
                </div>
                
                <div class="grid grid-cols-2 gap-4 mt-8">
                  <div class="card p-4">
                    <h2 class="text-2xl font-bold mb-2">Features</h2>
                    <ul class="list-disc pl-5">
                      <li>Advanced audio analysis</li>
                      <li>Stunning visualizations</li>
                      <li>Powerful editing tools</li>
                      <li>Collaborative workspaces</li>
                    </ul>
                  </div>
                  
                  <div class="card p-4">
                    <h2 class="text-2xl font-bold mb-2">Coming Soon</h2>
                    <ul class="list-disc pl-5">
                      <li>Mobile application</li>
                      <li>Enhanced collaborative features</li>
                      <li>AI-powered audio enhancement</li>
                      <li>Real-time collaboration</li>
                    </ul>
                  </div>
                </div>
                
                <footer class="mt-8 p-4 card">
                  <div class="flex items-center justify-between">
                    <p>© 2025 CymaSphere. All rights reserved.</p>
                  </div>
                </footer>
              </main>
            </body>
          </html>
          EOL
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 