# version 1
name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main # Trigger deployment on push to main branch
  workflow_dispatch: # Allow manual triggering from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies only (not Next.js build)
        uses: actions/cache@v4
        with:
          # Cache only dependencies, not Next.js build to avoid server action mismatches
          path: |
            ~/.npm
            ~/.bun
          key: ${{ runner.os }}-deps-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.1"

      - name: Set npm version
        run: npm install -g npm@10.9.2

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.13

      - name: Install dependencies
        run: bun install

      - name: Generate Supabase types
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: bun run gen-supabase-types

      - name: Clean build directory
        run: rm -rf .next

      - name: Build application
        env:
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          STRIPE_PRICE_ID_MONTHLY: ${{ secrets.STRIPE_PRICE_ID_MONTHLY }}
          STRIPE_PRICE_ID_ANNUAL: ${{ secrets.STRIPE_PRICE_ID_ANNUAL }}
          STRIPE_PRICE_ID_LIFETIME: ${{ secrets.STRIPE_PRICE_ID_LIFETIME }}
        run: bun run build

      - name: Configure SSH
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
        run: |
          # SSH configuration
          cat >> ~/.ssh/config << EOF
          Host $LIGHTSAIL_HOST
            User $LIGHTSAIL_USER
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            ConnectTimeout 30
            ServerAliveInterval 30
            ServerAliveCountMax 3
          EOF

      - name: Stop running application
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
        run: |
          # Stop the current application with proper Node.js environment
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "bash -l -c 'source ~/.nvm/nvm.sh && export PATH=\$(npm bin -g):\$PATH && pm2 stop cymasphere || true'"
          
          # Clean build artifacts on server to avoid server action mismatches
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "rm -rf ~/cymasphere/.next"

      - name: Copy files to server
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
        run: |
          # Create directories if they don't exist with proper structure
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "mkdir -p ~/cymasphere/.next ~/cymasphere/public"

          # Copy application files with proper directory structure using checksum-based comparison for efficiency
          rsync -avz --delete --checksum --partial --compress-level=6 -e "ssh -o ConnectTimeout=60" \
            .next/ $LIGHTSAIL_USER@$LIGHTSAIL_HOST:~/cymasphere/.next/

          # Copy public directory with all subdirectories, preserve permissions, and only transfer changed files
          rsync -avz --delete --checksum --partial --compress-level=6 --recursive --perms --times -e "ssh -o ConnectTimeout=60" \
            public/ $LIGHTSAIL_USER@$LIGHTSAIL_HOST:~/cymasphere/public/

          # Verify public directory structure was copied correctly
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "ls -la ~/cymasphere/public/"

          # Copy essential config files
          rsync -avz --checksum -e "ssh -o ConnectTimeout=60" \
            package.json bun.lock database.types.ts middleware.ts $LIGHTSAIL_USER@$LIGHTSAIL_HOST:~/cymasphere/

          # Create environment file (use .env.local for consistency with local development)
          echo "NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}" > .env.local
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}" >> .env.local
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env.local
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env.local
          echo "STRIPE_PRICE_ID_MONTHLY=${{ secrets.STRIPE_PRICE_ID_MONTHLY }}" >> .env.local
          echo "STRIPE_PRICE_ID_ANNUAL=${{ secrets.STRIPE_PRICE_ID_ANNUAL }}" >> .env.local
          echo "STRIPE_PRICE_ID_LIFETIME=${{ secrets.STRIPE_PRICE_ID_LIFETIME }}" >> .env.local

          # Copy environment file
          rsync -avz --checksum -e "ssh -o ConnectTimeout=60" \
            .env.local $LIGHTSAIL_USER@$LIGHTSAIL_HOST:~/cymasphere/

          # Copy next.config.js if it exists and has changed
          if [ -f "next.config.js" ]; then
            rsync -avz --checksum -e "ssh -o ConnectTimeout=60" \
              next.config.js $LIGHTSAIL_USER@$LIGHTSAIL_HOST:~/cymasphere/
          fi

          # Copy next.config.ts if it exists and has changed
          if [ -f "next.config.ts" ]; then
            rsync -avz --checksum -e "ssh -o ConnectTimeout=60" \
              next.config.ts $LIGHTSAIL_USER@$LIGHTSAIL_HOST:~/cymasphere/
          fi

      - name: Install dependencies on server
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
        run: |
          # Install dependencies with nvm sourcing and npm global bin path
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "bash -l -c 'source ~/.nvm/nvm.sh && cd ~/cymasphere && export PATH=\$(npm bin -g):\$PATH && bun install'"
          
          # Generate Supabase types on server to ensure they match
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "bash -l -c 'source ~/.nvm/nvm.sh && cd ~/cymasphere && export PATH=\$(npm bin -g):\$PATH && bun run gen-supabase-types'"

      - name: Start application
        env:
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
        run: |
          # Start application with nvm sourcing and npm global bin path
          ssh $LIGHTSAIL_USER@$LIGHTSAIL_HOST "bash -l -c 'source ~/.nvm/nvm.sh && cd ~/cymasphere && export PATH=\$(npm bin -g):\$PATH && pm2 describe cymasphere > /dev/null 2>&1 && pm2 restart cymasphere || pm2 start bun --name \"cymasphere\" -- start'"
