name: Deploy to AWS Lightsail (Fixed)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment'
        required: false
        default: 'false'

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
      
      - name: Create .env.local file for build
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" >> .env.local
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" >> .env.local
        
      - name: Debug directory structure
        run: |
          echo "Current directory structure:"
          ls -la
          echo "App directory:"
          ls -la app || echo "App directory not found!"

      - name: Make build script executable
        run: chmod +x ./build-no-errors.sh
        
      - name: Run enhanced build script
        run: ./build-no-errors.sh
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_SKIP_TYPECHECKING: true
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set lowercase repo owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create optimized Dockerfile
        run: |
          cat > Dockerfile << 'DOCKERFILE_EOF'
          FROM oven/bun:1 as base

          # Install dependencies
          FROM base AS deps
          WORKDIR /app
          COPY package.json bun.lock ./
          RUN bun install --frozen-lockfile

          # Build the application
          FROM base AS builder
          WORKDIR /app
          COPY --from=deps /app/node_modules ./node_modules
          COPY . .
          
          # Environment variables for build
          ENV NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          ENV NODE_ENV=production
          ENV NEXT_SKIP_TYPECHECKING=true
          ENV NEXT_TELEMETRY_DISABLED=1
          ENV NEXT_LINT=false
          
          # Run the build with error handling
          RUN chmod +x ./build-no-errors.sh && ./build-no-errors.sh
          
          # Make sure public directory exists
          RUN mkdir -p /app/public
          
          # Production image
          FROM base AS runner
          WORKDIR /app

          ENV NODE_ENV=production
          ENV NEXT_TELEMETRY_DISABLED=1
          ENV PORT=3000
          ENV HOSTNAME=0.0.0.0

          # Copy necessary files
          COPY --from=builder /app/.next/standalone ./
          COPY --from=builder /app/.next/static ./.next/static
          COPY --from=builder /app/public ./public

          # Create a startup script
          RUN echo '#!/bin/sh' > /app/start.sh && \
              echo 'echo "Starting server on port 3000..."' >> /app/start.sh && \
              echo 'if [ -f "server.js" ]; then' >> /app/start.sh && \
              echo '  node server.js' >> /app/start.sh && \
              echo 'else' >> /app/start.sh && \
              echo '  echo "Server.js not found, starting emergency server"' >> /app/start.sh && \
              echo '  node -e "require(\"http\").createServer((req,res)=>{res.writeHead(200,{\"Content-Type\":\"text/html\"});res.end(\"<html><body><h1>Cymasphere Website</h1><p>Maintenance mode active. Please check back shortly.</p></body></html>\");}).listen(3000,\"0.0.0.0\")"' >> /app/start.sh && \
              echo 'fi' >> /app/start.sh && \
              chmod +x /app/start.sh

          # Set the command to run
          CMD ["/app/start.sh"]
          DOCKERFILE_EOF

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER_LC }}/cymasphere-website:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: true
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          
      # Install SSH key using a more reliable approach
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS || '' }}
          name: id_rsa
          if_key_exists: replace

      # Add the Lightsail IP to known hosts
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.LIGHTSAIL_IP }} >> ~/.ssh/known_hosts

      - name: Create deployment script
        run: |
          cat > deploy_remote.sh << 'EOL'
          #!/bin/bash
          
          # Setup Docker if not already installed
          if ! command -v docker &> /dev/null; then
            echo "Docker not found, installing..."
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl gnupg
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg
            echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            sudo usermod -aG docker ubuntu
            sudo systemctl enable docker
            sudo systemctl start docker
          fi
          
          # Ensure proper permissions
          sudo usermod -aG docker ubuntu
          sudo chmod 666 /var/run/docker.sock
          
          # Login to GitHub Container Registry
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
          
          # Pull the latest image
          docker pull ghcr.io/${{ env.REPO_OWNER_LC }}/cymasphere-website:latest
          
          # Stop and remove any existing container
          docker stop cymasphere-container || true
          docker rm cymasphere-container || true
          
          # Run the new container
          echo "Starting container..."
          docker run -d --restart unless-stopped --name cymasphere-container \
            -p 80:3000 \
            -e NODE_ENV=production \
            -e PORT=3000 \
            -e HOSTNAME=0.0.0.0 \
            -e NEXT_PUBLIC_SUPABASE_URL="${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" \
            -e NEXT_PUBLIC_SUPABASE_ANON_KEY="${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" \
            ghcr.io/${{ env.REPO_OWNER_LC }}/cymasphere-website:latest
          
          # Verify deployment
          echo "Container status:"
          docker ps -a | grep cymasphere
          echo "Container logs:"
          docker logs cymasphere-container
          
          # Clean up
          docker system prune -af --volumes
          EOL
          
          chmod +x deploy_remote.sh

      - name: Deploy to Lightsail
        run: |
          # Test SSH connection first
          ssh -o StrictHostKeyChecking=no -vT ubuntu@${{ secrets.LIGHTSAIL_IP }} "echo SSH Connection Successful"
          
          # Then attempt to copy and run deploy script
          scp -o StrictHostKeyChecking=no deploy_remote.sh ubuntu@${{ secrets.LIGHTSAIL_IP }}:~/deploy.sh
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.LIGHTSAIL_IP }} "chmod +x ~/deploy.sh && ~/deploy.sh"
          
      - name: Verify deployment
        run: |
          # Check if the site is reachable
          echo "Verifying if site is accessible..."
          if curl -s --head --fail http://${{ secrets.LIGHTSAIL_IP }}; then
            echo "Site is accessible. Deployment successful!"
          else
            echo "Site is not accessible. Please check the server logs."
            exit 1
          fi 